### ISSUE TITLE
ReadTimeout happening during legacy enqueuing

### ISSUE THREAD

**Issue by pumazi** [Connexions/cnx-press#100]
We are experiencing `ReadTimeout` errors when the `press.subscribers.legacy_enqueue.legacy_enqueue` subscriber is run on larger data sets. See also https://sentry.cnx.org/openstax/press/issues/571/

The calls to legacy to 'enqueue' are reasonably fast, so it comes as a surprise that we're running into an issue with timeout. Ross has investigated the issue in the legacy software to determine that there are database (ZODB?) conflicts occurring.

Ross reasons to believe that the legacy queue implementation is unable to handle the speed at which we send these requests.

**Comment by reedstrm** [comment]
In particular, we're hitting conflicts on the persistentList object that is used to store the queue on the Lineup product instance (aka queue_tool).
