### ISSUE TITLE
Batch: Don't publish over another's publication

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-press#143]
As a Content Manager, when publishing with press, I want to be stopped (and given reason) if the version I am publishing will not be the next subsequent version, so that I do not publish over someone's work.

### Technical notes

The existing version of the content can be retrieved from the database (i.e. `modules.version`). The version of the document to be published can be parsed from the content's metadata (i.e. `<md:version>`).

## PRs
https://app.zenhub.com/workspace/o/connexions/cnx-press/issues/151

## Acceptance Criteria

- Content manager will be prompted during ```publish``` if their new version will not be the next version up, sequentially. (e.g. if CM is currently working on version 1.2 and upon ```publish``` the version will end up being 1.4 instead of 1.3)

**Comment by kerwinso** [comment]
This was working on qa for Bey, need to check staging.

https://openstax.slack.com/archives/C0LA54Q5C/p1533667224000099

```
Britneys-MacBook-Pro:nebuchadnezzar BritneyBlodget$ neb publish qa col12012 "no change just enqueue test"
ERROR: 
b'{"messages": [{"id": 3, "message": "stale version", "item": "m50979", "error": "checked out version is 1.7 but currently published is 1.8"}]}'
Stop the Press!!! =()
Britneys-MacBook-Pro:nebuchadnezzar BritneyBlodget$
```

**Comment by kerwinso** [comment]
We need a better Definition of Done for this, will discuss.

**Comment by kerwinso** [comment]
Decision from scrum 8/13/18: current behavior is acceptable. Bey will open another issue to handle improved error messaging.

Closing this issue.
