### ISSUE TITLE
Batch Image upload Story

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-press#144]
# Description
As a CM, I want to be able to edit, replace, delete, or rename images within a book I am editing, and publish those changes. [Currently not possible with neb/press/atom]

Depends on: https://trello.com/c/5doPuXfG/

Technical note: There are TODO comments in the code where this logic should simply fit in.

# Acceptance criteria

CMs should be able to use batch editing (already developed) to re-upload new images and use batch publishing to import those images and publish them onto the destination server. 

Revised files/images are published, imported and visible on the destination server.

If you change the file and it has the same name, it overrides it. 

**Note:** This does not conflict with removing rescources from the litezip. Resources are *not* downloaded with the litezip, but images can be uploaded with the new publishing payload for press. 

# Solution

More info in the:
Epic doc: https://docs.google.com/document/d/1h11YfVIxJkxv3k5os2VOQ5tml0fVIweHcgTk40Q1Pmw/edit#heading=h.v6dgaahg6si

and Content Manager Press doc: https://docs.google.com/document/d/1jrTzoAxNBS-sPjUP_TPqShT-KsyWr7RqMuFWSW-8eVk/edit

**Comment by BryanEliDimas** [comment]
Current status of my ongoing work towards this issue: My tests are failing locally even from the most up to date master branch. I need Ross to diagnose the issue as I suspect it has to do with the recent changes to cnx-db when we added authentication to neb/press.
