### ISSUE TITLE
Make batch publish not override locked-version PDF

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-press#145]
As a Content Manager, when I publish with Batch I _only_ want the collxml and complete zip to be enqueued **and** I want the locked PDF download link to remain the same (not rev up a version as the zip will); so that there will always be the "latest" version of the complete zip and a specific version of the PDF available for download. 

Above is the expected enqueueing behavior after a batch publish. This _was_ the behavior prior to the 7/30 release, therefore this is a regression and receiving the bug label. 

**Acceptance Criteria**
-------------------------------
- After a batch publish, only the collxml and complete zip will be enqueued
- The existing collection PDF link (pre-batch publish) under the downloads tab on _both_ cnx & legacy will not be removed or overidden. ![Screen_Shot_2018-07-30_at_10.44.34_AM.png](https://images.zenhubusercontent.com/5a01faba8a75884b90866af7/aeb65f49-4acb-4204-a163-d7e5c203d6be)

This is a screenshot of the downloads tab on CNX after a batch publish. The latest complete zip is available for download, but the PDF has been removed. Screen Shot 2018-07-30 at 10.44.34 AM.png

Note: the method used to fix this is to change the behavior of publishing via `press`, so that only the minor version of the collection will change, rather than a major version rev (and setting minor version to .1)

# PRs
#174

**Comment by reedstrm** [comment]
Discussed w/ @Dantemss , realized what y'all have been seeing is in some ways a bug  - the PDF offered for download does _not_ match the content being viewed, so should indicate that in some way. I'll file an issue against cnx-archive for that. However, we have a plan to restore this behavior when publishing via press, as discussed in scrum(s) - modify press to do a minor rev, initially for all publishes,  eventually detect if the collection structure has been changed, and only then do a major rev. Dante is working on this code, Bryan is working on the structure compare code.

**Comment by reedstrm** [comment]
I take it back, just found code in legacy that _copies the pdf over, if it's locked_ So. Hrmph.

**Comment by kerwinso** [comment]
@reedstrm to fill in more test plan details

**Comment by kerwinso** [comment]
@Bkblodget to test this on staging

**Comment by Dantemss** [comment]
We'll probably want to discuss @Bkblodget's concerns during scrum tomorrow.

**Comment by Bkblodget** [comment]
Verified on staging with col12012 (same behavior as test on qa).

Downloaded pdf (version number in title has changed but generation date on PDF is **not** current date - desired behavior):
![Screen Shot 2018-09-10 at 10.08.55 AM.png](https://images.zenhubusercontent.com/5b572db8a74e9a33056ecb3c/ebafd9e0-e9eb-4ec1-a4fe-4e335e47081f)

**Comment by Bkblodget** [comment]
Re-verified with more thorough testing on col11629.

Testing Steps:
1. enqueue the collection you are working with on staging.cnx
2. download the PDF of the collection from **production**.
3. use the below steps to push this pdf to staging.cnx:
     a. Open the Terminal application
     b. `cd Desktop`
     c. `curl -F value=@[NAME OF OPTIMIZED PDF YOU PUT ON YOUR DESKTOP].pdf -F extension=pdf https://legacy.cnx.org/content/[COLLECTION NUMBER]/[VERSION NUMBER]/setPrintedFile`
     d. **example**: `curl -F value=@CollegePhysicsforAPCourses-OP.pdf -F extension=pdf https://legacy.cnx.org/content/col11844/1.13/setPrintedFile`
     e. verify by downloading the pdf from the bookpage on staging.cnx
4. neb get collection
5. neb publish collection
6. after baking is complete, verify that the same PDF that was pushed remains by downloading the pdf from downloads tab (the title should reflect the new minor version number, but the download should be the same PDF prior to publishing with press).
