### ISSUE TITLE
Test: Update haproxy config to use capture.req.uri

### ISSUE THREAD

**Issue by brittweinstein** [Connexions/cnx-press#146]
birthed by #x-20180731-cnxdown

Update HAProxy to correctly point www.cnx.org to cnx.org so that logs have less clutter (PR created, merged, and slated for 8/13 release)

Fixes #701

you'll want to test this change for next deploy. Essentially, it's checking that www.cnx.org redirects to cnx.org.

PR: https://github.com/Connexions/cnx-deploy/pull/702#issuecomment-409362135

**Comment by pumazi** [comment]
This is a duplicate of connexions/cnx-deploy#701
