### ISSUE TITLE
Use the existing 'created' value rather than reading it from the document

### ISSUE THREAD

**Issue by pumazi** [Connexions/cnx-press#148]
We're currently reading the `created` datetime value from the parsed c*xml document before storing that info in the database. This isn't the correct thing to be doing. We should use the existing record's `created` value, so that the creation date cannot be accidentally or purposefully changed.

PR @ https://github.com/Connexions/cnx-press/pull/167

**Comment by Bkblodget** [comment]
Test plan: 
Publish collections with legacy editor and batch and see if the latest collection link works properly.

**Comment by Bkblodget** [comment]
More specifically look at the collexml & cnxml metadata for "created" and attempt to change.  After publishing with batch the change _should_ have been ignored.

**Comment by Bkblodget** [comment]
waiting to see if this has been deployed to QA

**Comment by kerwinso** [comment]
Ross needs to show K what's deployed on qa

**Comment by kerwinso** [comment]
@Bkblodget I verified that this change has been deployed to the qa server, you can start testing there.

```
kerwin@qa00:/var/cnx/apps/press$ git describe
v4.1.0-6-g5aa2133
kerwin@qa00:/var/cnx/apps/press$ git log
commit 5aa2133e4cba6f4a1646e84a30e018471239f1af
Author: Michael Mulich <pumazi@users.noreply.github.com>
Date:   Wed Aug 15 15:38:03 2018 -0700

    Use the existing record's 'created' value (#167)
```

**Comment by Bkblodget** [comment]
verified-ish on col11629
- changed created date and published with neb
- created date remained unchanged under the "More Information" tab on qa.cnx
- after using neb get to retrieve the updated zip, the created date was reverted back to original created date (not the altered one from the previous edit) - **Is this the correct behavior?**

**Comment by Bkblodget** [comment]
Verified on staging with col12012 (same behavior as test on qa).
