### ISSUE TITLE
Batch  Authentication

### ISSUE THREAD

**Issue by Bkblodget** [Connexions/cnx-press#186]
##### Description
As OpenStax management, I want to have strict control over who can publish via Press, so that our content is protected from unauthorized tampering.

##### Acceptance criteria
Press only accepts authenticated publication requests.
Press will only allow authorized users to publish (based on content permissions).

#### Desired workflow:
1) User does neb get for a collection (unauthenticated)
2) User makes changes in Atom
3) User does neb publish.
       a) Neb prompts for message (if not given via `-m/--message` switch)
       b) Neb prompts for username, if not given via `u/--username` ~(If there is a username in the config file for this environment, use as default.)~
       c) Neb prompts for password (if not given via `-p/--password`)
4) Press authenticates that (a) the password is correct, and (b) the account is a global maintainer

#### Testing legacy sync -
1. Create a new account on legacy. Verify that it is _not_ be able to publish via `neb/press`
2. As a manager, give the new account the `Maintainer` role. Verify that the account can now publish via `neb`

## PRs
This repo: https://github.com/Connexions/cnx-press/pull/199
Neb repo: https://github.com/Connexions/nebuchadnezzar/pull/78

### Additional PRs in Rhaptos (for syncing the credentials from legacy - all merged):
passwords:
https://github.com/Rhaptos/Products.RhaptosSite/commit/05c9125daa7db814712376a0fb3ee4a825faeb52
https://github.com/Rhaptos/Products.RhaptosModuleStorage/pull/23
groups:
https://github.com/Rhaptos/Products.RhaptosSite/pull/7
https://github.com/Rhaptos/Products.RhaptosModuleStorage/pull/22

**Comment by pumazi** [comment]
See also:

- Configure inclusion point: https://github.com/Connexions/cnx-publishing/blob/master/cnxpublishing/config.py#L83
- Detailed configuration available at: https://github.com/Connexions/cnx-publishing/blob/master/cnxpublishing/authnz.py#L93-L107
- Authentication and Authorization Policies: https://github.com/Connexions/cnx-publishing/blob/master/cnxpublishing/authnz.py
- Root object that defines permissions: https://github.com/Connexions/cnx-publishing/blob/master/cnxpublishing/config.py#L20-L48

**Comment by reedstrm** [comment]
Oh useful, thanks, @pumazi

**Comment by Bkblodget** [comment]
After my username was manually added to DB and my password changed I was able to verify this new feature and regression test with no errors.

**Comment by reedstrm** [comment]
Additional PRs in Rhaptos (for syncing the credentials from legacy - all merged):

https://github.com/Rhaptos/Products.RhaptosSite/pull/7
https://github.com/Rhaptos/Products.RhaptosModuleStorage/pull/22
https://github.com/Rhaptos/Products.RhaptosModuleStorage/pull/23
