### ISSUE TITLE
cnxml files published via neb and press are not utf-8 encoded

### ISSUE THREAD

**Issue by kerwinso** [Connexions/cnx-press#196]
cnxml files are not utf-8 encoded, instead they are escape encoded.

not sure if this is due to neb or press. but press should re-encode these files as UTF-8.
this is NOT due to Atom.

## PRs
https://github.com/Connexions/cnx-press/pull/204

**Comment by openstaxalina** [comment]
@kerwinso, could you clarify the end user impact for this?  For example, is the Batch user currently receiving an error, or unable to publish?  Or perhaps - is there a risk of the OpenStax user seeing outdated content?  Thank you for helping me understand this!

**Comment by kerwinso** [comment]
@openstaxalina : I had just jotted this down for @reedstrm after he noticed something, he can provide more details.

**Comment by openstaxalina** [comment]
One user impact is that @Bkblodget can no longer effectively locate search terms using Atom in a collection that was previously published by Batch.

**Comment by reedstrm** [comment]
@Bkblodget could you give me a link to files on production that have been affected this way?

**Comment by reedstrm** [comment]
Nevermind - col11629 seems to be a good example

**Comment by Bkblodget** [comment]
Verified on col11629
