### ISSUE TITLE
Batch Tree Collection numbering for sub-collection numbering

### ISSUE THREAD

**Issue by Bkblodget** [Connexions/cnx-press#251]
## Overview
The tree collection is assigning "01" to all introduction modules within a sub-collection (chapter). This throws off the module numbering when comparing to webview because the TOC in webview does **not** assign numbering to introduction modules. 
## PRs
What PRs need to be merged to complete this task/feature
## Test Plan
@Bkblodget to use neb to get a collection and ensure the numbering matches webview in both the finder directory and atom. 
## Acceptance Criteria
-collection tree numbering from batch matches numbering in webview

**Comment by reedstrm** [comment]
Issue moved to [Connexions/nebuchadnezzar #90](https://github.com/Connexions/nebuchadnezzar/issues/90) via [**ZenHub**](https://www.zenhub.com/)
