### ISSUE TITLE
Press should detect a major revision (within collxml). [Priority 4]

### ISSUE THREAD

**Issue by Bkblodget** [Connexions/cnx-press#266]
## Description ##
Press needs to detect whether a major version rev is needed for the collection. This is priority #4 for the Only Publish Changed Content epic. 

The ONLY criteria for a major version rev:
- Collection structure change (adding, removing, reordering)
- Collection title change

## Technical Notes ##
- 
- 

## Acceptance Criteria ##
If the collection structure or title is altered, Press will rev the major version of the collection upon publish.

## Test Plan ##
- Major version rev should ONLY happen with the criteria listed. Test changing other things like collection metadata (print style, summary, keywords) and make sure a major version rev does not happen. 
-

**Comment by openstaxalina** [comment]
Closing because this is covered with https://app.zenhub.com/workspaces/cnx-team-5af1f4cc12da5e6d74331b60/issues/connexions/cnx-press/162
