### ISSUE TITLE
publishing does not update revised

### ISSUE THREAD

**Issue by reedstrm** [Connexions/cnx-press#81]
Both module and collection publishing pass on the revised timestamp from the metadata:

https://github.com/Connexions/cnx-press/blob/master/press/legacy_publishing/module.py#L54
https://github.com/Connexions/cnx-press/blob/master/press/legacy_publishing/collection.py#L55

While this accurately tracks what legacy/zope did, that system tightly coupled the client editor and the publishing, so the revised timestamp on the edited object could be in fact trusted. Press should either allow the database to fill in the current transaction's CURRENT_TIMESTAMP (one way or another) or provide it's own "publication time" stamp.

**Comment by kerwinso** [comment]
Verified fix in https://github.com/Connexions/nebuchadnezzar/issues/35.
