### ISSUE TITLE
GA codes disappear on publish

### ISSUE THREAD

**Issue by reedstrm** [Connexions/cnx-press#84]
When publishing an existing collection w/ press, the existing GA codes go away. This is probably because the collxml metadata does not include the GA codes, so there is no code to handle updating them.

**Comment by pumazi** [comment]
@reedstrm wrote in slack:
> I can modify RhaptosCollection to emit it, just not sure where to put it. Another `col:param` perhaps? mdml doesn't have a catch-all attribute like that. Of course, I have to rev mdml to solve the derived-copy problem anyway …

**Comment by pumazi** [comment]
Sounds like a good long-term plan. I don't know that anyone is asking for the ability to set a GA code at the moment. So the more immediate fix would be to copy the GA code from the previous version. We'll then let the users decide on the priority of the long-term solution or you'll have casually implemented a portion of this while adjusting the mdml for the derived-copy story.

**Comment by kerwinso** [comment]
@pumazi wrote:
> So the more immediate fix would be to copy the GA code from the previous version.

Would this code then have to be manually pasted in to legacy after publishing with press?

**Comment by reedstrm** [comment]
ok   - settled on @pumazi 's plan above

**Comment by kerwinso** [comment]
Re-opening to verify.

**Comment by kerwinso** [comment]
Re-published Principles of Econ, this appears to be fixed. Google Analytics codes intact for both book and page.

https://archive-qa.cnx.org/contents/69619d2b-68f0-44b0-b074-a9b2bf90b2c6@13.1.json

https://archive-qa.cnx.org/contents/9ff3ce08-0471-4d79-81d7-6a57a308d142@13.json
