### ISSUE TITLE
Publishing clears print-style setting

### ISSUE THREAD

**Issue by reedstrm** [Connexions/cnx-press#86]
Unlike the google-analytics code, the print-style _is_ present in the collection.xml:
```
col11448_1.11_complete$ grep print-style collection.xml 
    <col:param name="print-style" value="biology"/>
```
I'm betting litezip is partly to blame for not parsing it into a model attribute, but press will still need to update it.

**Comment by reedstrm** [comment]
Actually, litezip is content-agnostic, so I guess this is up to press to parse out of the collection.xml?

**Comment by kerwinso** [comment]
Re-opening to verify.

**Comment by kerwinso** [comment]
Re-published Principles of Econ col11613, this appears to be fixed. `printStyle` is intact in the json: https://archive-qa.cnx.org/contents/69619d2b-68f0-44b0-b074-a9b2bf90b2c6@13.1.json

Webview looks ok: https://qa.cnx.org/contents/aWGdK2jw@13.1:9OsyQxeW@17/322-Improving-Countries-Standa
